# Generated by Django 3.1.2 on 2020-10-28 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0002_summoner'),
    ]

    operations = [
        migrations.AddField(
            model_name='summoner',
            name='name',
            field=models.CharField(default='baasje', max_length=200),
            preserve_default=False,
        ),
    ]
