# Generated by Django 3.1.3 on 2020-11-30 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0003_summoner_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('match_id', models.PositiveBigIntegerField(primary_key=True, serialize=False)),
                ('match_data', models.JSONField()),
            ],
        ),
    ]
