# Generated by Django 3.1.3 on 2020-11-30 20:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0004_match'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Match',
        ),
    ]
