# Generated by Django 3.1.3 on 2020-11-30 20:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0004_match'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match',
            name='summoners',
        ),
        migrations.AddField(
            model_name='match',
            name='result',
            field=models.JSONField(default={}),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='SummonerMatch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_id', models.IntegerField()),
                ('summoner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='teams.summoner')),
            ],
        ),
    ]
