# Generated by Django 3.1.3 on 2020-11-30 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0005_delete_match'),
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('match_id', models.PositiveBigIntegerField(primary_key=True, serialize=False)),
                ('match_data', models.JSONField()),
            ],
        ),
    ]
